### PR TITLE
Add the original copy as taken from Archive.org Xerox PARC FTP snapshot

### PR DESCRIPTION
**Pull request by fb08af68**
Right now it is not really clear whether there is an unedited copy lying around. The best . I propose adding an explicit original copy which is not to be changed. These 7MiB (uncompressed) of text seems to be available either inside a 1GiB zip, or as 158 files inside a large torrent, neither option seems too user-friendly.

### CODE REVIEW

**Comment by phoe** [comment]
The version you have uploaded is dpANS2. The recentmost version is dpANS3.
https://github.com/antoszka/dpANS3 contains it.

**Comment by fb08af68** [comment]
Well, Franz had some reason to start with dpANS2, so isn't it safer to start with dpANS2?

**Comment by phoe** [comment]
I see no such a reason - dpANS3 contains additional minor fixes and changes in the specification text that makes it functionally equivalent to the CL standard where dpANS2 is not.

Additionally, CLUS is based on dpANS3, so I find completely no sense in including the non-source dpANS2 in a CLUS repository.

**Comment by fb08af68** [comment]
Is dpANS3 _different_ enough from standard for safety?

**Comment by phoe** [comment]
Yes - it is not called ANSI Common Lisp.

**Comment by phoe** [comment]
Since dpans3 is available at https://github.com/antoszka/dpans3 and https://github.com/xach/dpans for example - I will be closing this issue.

**Pull request closed without merging**
